### ISSUE TITLE
Configuración Subdominio 

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/angular-weekend-2018#1]
@cronopio Necesitamos la configuración de un subdominio para la landing del evento:
`angular-weekend.pereirajs.org` y que apunte a este repositorio.
_Nota: Ya se agregó el archivo CNAME_

**Comment by pin3da** [comment]
Hola, hablando con todos decidimos que era mejor `angular.pereira.js`

@cronopio  nos podrías ayudar porfa para configurar este sub dominio ?

**Comment by santiaguf** [comment]
@cronopio  el subdominio solicitado es: https://angular.pereirajs.org

**Comment by cronopio** [comment]
Hola Amiguitos. Pueden confirmarme si ya quedo listo?. El dominio desde hace varios meses esta siendo gestionado en una cuenta de CloudFlare, por lo tanto debe ser alli donde se hagan las configuraciones de DNS que necesitan. Hay que aclarar que yo no tengo acceso a esa cuenta de CloudFlare.

Saludos!

**Comment by pin3da** [comment]
@cronopio, ya está funcionando bien. Muchas gracias !
