### ISSUE TITLE
UX Hacer más claro que hay más contenido

### ISSUE THREAD

**Issue by jonalvarezz** [pereirajs/angular-weekend-2018#7]
Problema: Luego que las animaciones del hero cargan, no es directamente claro que hay más contenido. El hero ocupa todo el pantalla, la navegación está oculta y el texto parece que sólo anunciara el evento.

Considero es un problema de UX y puede causar confusión

Posibles soluciones:
– Agregar un enlace de Ver Más/ Más información o cualquier otro call to action para llevar al visitante al contenido o al registro.
– No ocultar el Navbar
– Que el hero no ocupe el 100% del alto de forma que el contenido alcance a asomarse.

**Comment by jdmorales** [comment]
@jonalvarezz Es cierto, también lo estaba pensando. Yo creo que con los primeros dos puntos se resuelve el problema de UX que comentas. El alto pienso que ya no sería tan necesario cambiarlo.

**Comment by jonalvarezz** [comment]
@jdmorales Realmente creo que con el primero ya se soluciona y no cambia mucho el diseño que ya tienen.
